version: '3.4'

services:
  foodika:
    image: foodika
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - ".env"
    ports:
      - 80:80
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"